server:
  port: 8088
logging:
  level:
    mallfe.demo: debug
    # org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5es50j9lfj56x323jo.mysql.rds.aliyuncs.com:3306/alpha?allowMulitQueries=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: Tonsan123
#    url: jdbc:mysql://10.1.0.213:3306/ds_dsdq_test
#    username: test
#    password: 123456
mybatis:
  # mapper-locations: mapper/*.xml
  type-aliases-package: mallfe.demo.pojo