server:
  port: 8088
logging:
  level:
    mallfe.demo: debug
    # org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-m5es50j9lfj56x323jo.mysql.rds.aliyuncs.com:3306/alpha
    username: root
    password: Tonsan123
mybatis:
  # mapper-locations: mapper/*.xml
  type-aliases-package: mallfe.demo.pojo
